# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: voicesapp_development
  pool: 5
  username: voices
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: voicesapp_test
  pool: 5
  username: voices
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: voicesapp_production
  pool: 5
  username: voices
  password:
