# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f007d2682997c1470df905500473145284b52c5523f182431274226eaa2ff0c9b86e1fb28beae5d087da2e5573e5fc127af61ae357283a28af83480acdd6fd5e

test:
  secret_key_base: 870d215ae9b018c8e72b13ad2753d4482d86e943cbddd62679ac245cbcbc6641992b637f2330703a93322b56228f2b6355d2fcb441cf2d7d3281a83e616008ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
